import os
from collections.abc import Sequence
from typing import Any, Literal, final

from . import Library

__all__ = [
    "magnitude",
    "stress",
    "flow",
    "observation",
    "relation",
    "spectral",
    "seam",
    "echo",
    "orbit",
    "shape",
    "gravity",
    "context",
    "MagnitudeFrame",
    "MagnitudeReport",
    "StressFrame",
    "StressReport",
    "FlowFrame",
    "AnalyticFrame",
    "FlowReport",
    "ObservationFrame",
    "ObservationReport",
    "RelationFrame",
    "RelationEdge",
    "RelationChord",
    "RelationReport",
    "SpectralFrame",
    "SpectralPeriod",
    "TextureRegion",
    "ClassifiedRegion",
    "SpectralReport",
    "Segment",
    "SeamFrame",
    "SeamReport",
    "EchoFrame",
    "Echo",
    "EchoReport",
    "OrbitToken",
    "OrbitClass",
    "OrbitReport",
    "ShapeFrame",
    "ShapeRegion",
    "ShapeReport",
    "GravityFrame",
    "GravityClass",
    "GravityReport",
    "ContextMagnitude",
    "ContextStress",
    "ContextSpectral",
    "ContextEcho",
    "ContextObservation",
    "ContextSeam",
    "ContextFlow",
    "ContextFrame",
    "ContextAlignment",
    "ContextAgreement",
    "ContextReport",
]

_Text = str | bytes
_Path = str | os.PathLike[str]
_Lib = Library | _Path | Sequence[_Path]
_Texture = Literal["prose", "code", "math", "data", "mixed"]
_Grain = Literal["byte", "token", "super"]
_Fold = Literal["window", "unit", "units", "enclosing", "echo", "regime", "phase", "key"]

@final
class MagnitudeFrame:
    @property
    def offset(self) -> int: ...
    @property
    def text(self) -> str | bytes: ...
    @property
    def magnitude(self) -> float: ...
    @property
    def gradient(self) -> float: ...
    @property
    def energy(self) -> float: ...
    def to_dict(self) -> dict[str, Any]: ...

@final
class MagnitudeReport:
    @property
    def path(self) -> str | None: ...
    @property
    def length(self) -> int: ...
    @property
    def tokens(self) -> int: ...
    @property
    def total_energy(self) -> float: ...
    @property
    def peak(self) -> MagnitudeFrame | None: ...
    @property
    def jumps(self) -> list[MagnitudeFrame]: ...
    @property
    def outliers(self) -> list[MagnitudeFrame]: ...
    @property
    def frames(self) -> list[MagnitudeFrame]: ...
    def to_dict(self) -> dict[str, Any]: ...

@final
class StressFrame:
    @property
    def offset(self) -> int: ...
    @property
    def text(self) -> str | bytes: ...
    @property
    def depth(self) -> int: ...
    @property
    def strain(self) -> float: ...
    @property
    def load(self) -> float: ...
    def to_dict(self) -> dict[str, Any]: ...

@final
class StressReport:
    @property
    def path(self) -> str | None: ...
    @property
    def length(self) -> int: ...
    @property
    def tokens(self) -> int: ...
    @property
    def max_depth(self) -> int: ...
    @property
    def peak_load(self) -> StressFrame | None: ...
    @property
    def peaks(self) -> list[StressFrame]: ...
    @property
    def fractures(self) -> list[StressFrame]: ...
    @property
    def frames(self) -> list[StressFrame]: ...
    def to_dict(self) -> dict[str, Any]: ...

@final
class FlowFrame:
    @property
    def offset(self) -> int: ...
    @property
    def text(self) -> str | bytes: ...
    @property
    def slope(self) -> float: ...
    @property
    def direction(self) -> Literal["rising", "falling", "steady"]: ...
    @property
    def momentum(self) -> int: ...
    def to_dict(self) -> dict[str, Any]: ...

@final
class AnalyticFrame:
    @property
    def offset(self) -> int: ...
    @property
    def text(self) -> str | bytes: ...
    @property
    def amplitude(self) -> float: ...
    @property
    def phase(self) -> float: ...
    @property
    def frequency(self) -> float: ...
    def to_dict(self) -> dict[str, Any]: ...

@final
class FlowReport:
    @property
    def path(self) -> str | None: ...
    @property
    def length(self) -> int: ...
    @property
    def tokens(self) -> int: ...
    @property
    def grain(self) -> Literal["token", "super"]: ...
    @property
    def units(self) -> int: ...
    @property
    def signal(self) -> Literal["magnitude", "stress", "length"]: ...
    @property
    def peak_momentum(self) -> FlowFrame | None: ...
    @property
    def reversals(self) -> list[FlowFrame]: ...
    @property
    def frames(self) -> list[FlowFrame]: ...
    @property
    def latency(self) -> int | None: ...
    @property
    def analytic(self) -> list[AnalyticFrame]: ...
    def to_dict(self) -> dict[str, Any]: ...

@final
class ObservationFrame:
    @property
    def offset(self) -> int: ...
    @property
    def text(self) -> str | bytes: ...
    @property
    def causal(self) -> float: ...
    @property
    def anticausal(self) -> float: ...
    @property
    def centered(self) -> float: ...
    @property
    def disagreement(self) -> float: ...
    def to_dict(self) -> dict[str, Any]: ...

@final
class ObservationReport:
    @property
    def path(self) -> str | None: ...
    @property
    def length(self) -> int: ...
    @property
    def grain(self) -> _Grain: ...
    @property
    def units(self) -> int: ...
    @property
    def peak(self) -> ObservationFrame | None: ...
    @property
    def contested(self) -> list[ObservationFrame]: ...
    @property
    def frames(self) -> list[ObservationFrame]: ...
    def to_dict(self) -> dict[str, Any]: ...

@final
class GravityFrame:
    @property
    def offset(self) -> int: ...
    @property
    def text(self) -> str | bytes: ...
    @property
    def strain(self) -> float | None: ...
    @property
    def strain_percentile(self) -> float | None: ...
    @property
    def bound(self) -> float | None: ...
    @property
    def bound_percentile(self) -> float | None: ...
    @property
    def class_(self) -> int | None: ...
    def to_dict(self) -> dict[str, Any]: ...

@final
class GravityClass:
    @property
    def class_(self) -> int: ...
    @property
    def types(self) -> list[str]: ...
    @property
    def units(self) -> int: ...
    def to_dict(self) -> dict[str, Any]: ...

@final
class GravityReport:
    @property
    def path(self) -> str | None: ...
    @property
    def length(self) -> int: ...
    @property
    def grain(self) -> _Grain: ...
    @property
    def units(self) -> int: ...
    @property
    def types(self) -> int: ...
    @property
    def strained(self) -> list[GravityFrame]: ...
    @property
    def weakest(self) -> list[GravityFrame]: ...
    @property
    def classes(self) -> list[GravityClass]: ...
    @property
    def frames(self) -> list[GravityFrame]: ...
    def to_dict(self) -> dict[str, Any]: ...

@final
class ContextMagnitude:
    @property
    def mean(self) -> float: ...
    @property
    def spread(self) -> float: ...
    @property
    def max(self) -> float: ...
    def to_dict(self) -> dict[str, Any]: ...

@final
class ContextStress:
    @property
    def mean(self) -> float: ...
    @property
    def max(self) -> int: ...
    def to_dict(self) -> dict[str, Any]: ...

@final
class ContextSpectral:
    @property
    def entropy(self) -> float: ...
    @property
    def period(self) -> int: ...
    @property
    def strength(self) -> float: ...
    def to_dict(self) -> dict[str, Any]: ...

@final
class ContextEcho:
    @property
    def novel(self) -> int: ...
    @property
    def echoed(self) -> int: ...
    def to_dict(self) -> dict[str, Any]: ...

@final
class ContextObservation:
    @property
    def causal(self) -> float: ...
    @property
    def anticausal(self) -> float: ...
    @property
    def centered(self) -> float: ...
    @property
    def disagreement(self) -> float: ...
    @property
    def disagreement_max(self) -> float: ...
    @property
    def contested(self) -> int: ...
    def to_dict(self) -> dict[str, Any]: ...

@final
class ContextSeam:
    @property
    def forward(self) -> float: ...
    @property
    def backward(self) -> float: ...
    @property
    def strength(self) -> float: ...
    @property
    def strength_max(self) -> float: ...
    @property
    def cuts(self) -> int: ...
    def to_dict(self) -> dict[str, Any]: ...

@final
class ContextFlow:
    @property
    def slope(self) -> float: ...
    @property
    def rising(self) -> int: ...
    @property
    def falling(self) -> int: ...
    @property
    def steady(self) -> int: ...
    @property
    def momentum(self) -> int: ...
    @property
    def reversals(self) -> int: ...
    def to_dict(self) -> dict[str, Any]: ...

@final
class ContextFrame:
    @property
    def offset(self) -> int: ...
    @property
    def text(self) -> str | bytes: ...
    @property
    def phase(self) -> int | None: ...
    @property
    def over(self) -> int: ...
    @property
    def magnitude(self) -> ContextMagnitude | None: ...
    @property
    def stress(self) -> ContextStress | None: ...
    @property
    def spectral(self) -> ContextSpectral | None: ...
    @property
    def echo(self) -> ContextEcho | None: ...
    @property
    def observation(self) -> ContextObservation | None: ...
    @property
    def seam(self) -> ContextSeam | None: ...
    @property
    def flow(self) -> ContextFlow | None: ...
    def to_dict(self) -> dict[str, Any]: ...

@final
class ContextAlignment:
    @property
    def regime(self) -> float: ...
    @property
    def shape(self) -> float: ...
    @property
    def seam(self) -> float: ...
    def to_dict(self) -> dict[str, Any]: ...

@final
class ContextAgreement:
    @property
    def offset(self) -> int: ...
    @property
    def text(self) -> str | bytes: ...
    @property
    def role(self) -> Literal["call", "assign", "kv", "list", "numeric", "plain"]: ...
    @property
    def regime(self) -> int | None: ...
    @property
    def shape(self) -> int | None: ...
    @property
    def seam(self) -> int | None: ...
    def to_dict(self) -> dict[str, Any]: ...

@final
class ContextReport:
    @property
    def path(self) -> str | None: ...
    @property
    def length(self) -> int: ...
    @property
    def fold(self) -> _Fold: ...
    @property
    def tokens(self) -> int: ...
    @property
    def units(self) -> int: ...
    @property
    def period(self) -> int | None: ...
    @property
    def live_periods(self) -> list[int]: ...
    @property
    def alignment(self) -> ContextAlignment: ...
    @property
    def agreement(self) -> list[ContextAgreement]: ...
    @property
    def frames(self) -> list[ContextFrame]: ...
    def to_dict(self) -> dict[str, Any]: ...

@final
class RelationFrame:
    @property
    def offset(self) -> int: ...
    @property
    def text(self) -> str | bytes: ...
    @property
    def depth(self) -> int: ...
    @property
    def enclosure(self) -> list[str | bytes]: ...
    def to_dict(self) -> dict[str, Any]: ...

@final
class RelationEdge:
    @property
    def kind(self) -> Literal["encloses", "operator", "adjacent"]: ...
    @property
    def from_(self) -> str | bytes: ...
    @property
    def to(self) -> str | bytes: ...
    @property
    def from_offset(self) -> int: ...
    @property
    def to_offset(self) -> int: ...
    def to_dict(self) -> dict[str, Any]: ...

@final
class RelationChord:
    @property
    def from_(self) -> str | bytes: ...
    @property
    def to(self) -> str | bytes: ...
    @property
    def residual(self) -> int: ...
    @property
    def from_offset(self) -> int: ...
    @property
    def to_offset(self) -> int: ...
    def to_dict(self) -> dict[str, Any]: ...

@final
class RelationReport:
    @property
    def path(self) -> str | None: ...
    @property
    def length(self) -> int: ...
    @property
    def tokens(self) -> int: ...
    @property
    def max_depth(self) -> int: ...
    @property
    def nesting_load(self) -> int: ...
    @property
    def encloses(self) -> int: ...
    @property
    def operators(self) -> int: ...
    @property
    def adjacencies(self) -> int: ...
    @property
    def reuse_chords(self) -> int: ...
    @property
    def scope_crossing_chords(self) -> int: ...
    @property
    def holonomy(self) -> int: ...
    @property
    def net_holonomy(self) -> int: ...
    @property
    def boundary_events(self) -> int: ...
    @property
    def bulk_nodes(self) -> int: ...
    @property
    def holographic_defect(self) -> int: ...
    @property
    def boundary_closed(self) -> bool: ...
    @property
    def rebuilt_edges(self) -> int: ...
    @property
    def min_ricci(self) -> int: ...
    @property
    def mean_ricci(self) -> float: ...
    @property
    def bridges(self) -> int: ...
    @property
    def nodes(self) -> int: ...
    @property
    def graph_edges(self) -> int: ...
    @property
    def components(self) -> int: ...
    @property
    def cycle_rank(self) -> int: ...
    @property
    def euler(self) -> int: ...
    @property
    def max_shortcut(self) -> int: ...
    @property
    def peak_entanglement(self) -> int: ...
    @property
    def minimal_cut(self) -> int | None: ...
    @property
    def minimal_cut_offset(self) -> int | None: ...
    @property
    def canonical(self) -> str | None: ...
    @property
    def edges(self) -> list[RelationEdge]: ...
    @property
    def chords(self) -> list[RelationChord]: ...
    @property
    def frames(self) -> list[RelationFrame]: ...
    def to_dict(self) -> dict[str, Any]: ...

@final
class SpectralFrame:
    @property
    def offset(self) -> int: ...
    @property
    def texture(self) -> _Texture: ...
    @property
    def entropy(self) -> float: ...
    @property
    def period(self) -> int: ...
    @property
    def novelty(self) -> float: ...
    @property
    def mix(self) -> list[float]: ...
    def to_dict(self) -> dict[str, Any]: ...

@final
class SpectralPeriod:
    @property
    def period(self) -> int: ...
    @property
    def strength(self) -> float: ...
    def to_dict(self) -> dict[str, Any]: ...

@final
class TextureRegion:
    @property
    def offset(self) -> int: ...
    @property
    def length(self) -> int: ...
    @property
    def texture(self) -> _Texture: ...
    @property
    def entropy(self) -> float: ...
    @property
    def period(self) -> int: ...
    @property
    def novelty(self) -> float: ...
    def to_dict(self) -> dict[str, Any]: ...

@final
class ClassifiedRegion:
    @property
    def offset(self) -> int: ...
    @property
    def length(self) -> int: ...
    @property
    def kind(self) -> Literal["table", "blob", "prose", "numeric", "code", "mixed"]: ...
    @property
    def period(self) -> int: ...
    def to_dict(self) -> dict[str, Any]: ...

@final
class SpectralReport:
    @property
    def path(self) -> str | None: ...
    @property
    def length(self) -> int: ...
    @property
    def hop(self) -> int: ...
    @property
    def change_points(self) -> list[int]: ...
    @property
    def entropy_minimum(self) -> float | None: ...
    @property
    def entropy_mean(self) -> float | None: ...
    @property
    def entropy_maximum(self) -> float | None: ...
    @property
    def periods(self) -> list[SpectralPeriod]: ...
    @property
    def timeline(self) -> list[TextureRegion]: ...
    @property
    def regions(self) -> list[ClassifiedRegion]: ...
    @property
    def frames(self) -> list[SpectralFrame]: ...
    def to_dict(self) -> dict[str, Any]: ...

@final
class Segment:
    @property
    def offset(self) -> int: ...
    @property
    def length(self) -> int: ...
    @property
    def text(self) -> str | bytes: ...
    def to_dict(self) -> dict[str, Any]: ...

@final
class SeamFrame:
    @property
    def offset(self) -> int: ...
    @property
    def text(self) -> str | bytes: ...
    @property
    def forward(self) -> float: ...
    @property
    def backward(self) -> float: ...
    @property
    def boundary(self) -> float: ...
    def to_dict(self) -> dict[str, Any]: ...

@final
class SeamReport:
    @property
    def path(self) -> str | None: ...
    @property
    def length(self) -> int: ...
    @property
    def order(self) -> int: ...
    @property
    def segments(self) -> list[Segment]: ...
    @property
    def frames(self) -> list[SeamFrame]: ...
    def to_dict(self) -> dict[str, Any]: ...

@final
class EchoFrame:
    @property
    def offset(self) -> int: ...
    @property
    def text(self) -> str | bytes: ...
    @property
    def count(self) -> int: ...
    @property
    def nth(self) -> int: ...
    @property
    def previous(self) -> int | None: ...
    def to_dict(self) -> dict[str, Any]: ...

@final
class Echo:
    @property
    def key(self) -> str | bytes: ...
    @property
    def count(self) -> int: ...
    @property
    def period(self) -> float | None: ...
    @property
    def offset(self) -> int: ...
    def to_dict(self) -> dict[str, Any]: ...

@final
class EchoReport:
    @property
    def path(self) -> str | None: ...
    @property
    def length(self) -> int: ...
    @property
    def group(self) -> str: ...
    @property
    def tokens(self) -> int: ...
    @property
    def keyed(self) -> int: ...
    @property
    def distinct(self) -> int: ...
    @property
    def novel(self) -> int: ...
    @property
    def echoed(self) -> int: ...
    @property
    def novelty(self) -> float: ...
    @property
    def echo_rate(self) -> float: ...
    @property
    def echoes(self) -> list[Echo]: ...
    @property
    def structures(self) -> list[Echo]: ...
    @property
    def frames(self) -> list[EchoFrame]: ...
    def to_dict(self) -> dict[str, Any]: ...

@final
class OrbitToken:
    @property
    def offset(self) -> int: ...
    @property
    def length(self) -> int: ...
    @property
    def text(self) -> str | bytes: ...
    @property
    def orbit(self) -> str: ...
    def to_dict(self) -> dict[str, Any]: ...

@final
class OrbitClass:
    @property
    def orbit(self) -> str: ...
    @property
    def forms(self) -> list[str | bytes]: ...
    def to_dict(self) -> dict[str, Any]: ...

@final
class OrbitReport:
    @property
    def path(self) -> str | None: ...
    @property
    def length(self) -> int: ...
    @property
    def group(self) -> str: ...
    @property
    def tokens(self) -> int: ...
    @property
    def forms(self) -> int: ...
    @property
    def orbits(self) -> int: ...
    @property
    def classes(self) -> list[OrbitClass]: ...
    @property
    def matches(self) -> list[OrbitToken]: ...
    @property
    def segments(self) -> list[Segment]: ...
    @property
    def frames(self) -> list[OrbitToken]: ...
    def to_dict(self) -> dict[str, Any]: ...

@final
class ShapeFrame:
    @property
    def offset(self) -> int: ...
    @property
    def text(self) -> str | bytes: ...
    @property
    def class_(self) -> int: ...
    @property
    def period(self) -> int: ...
    @property
    def period_strength(self) -> float: ...
    @property
    def novelty(self) -> float: ...
    def to_dict(self) -> dict[str, Any]: ...

@final
class ShapeRegion:
    @property
    def offset(self) -> int: ...
    @property
    def length(self) -> int: ...
    @property
    def period(self) -> int: ...
    def to_dict(self) -> dict[str, Any]: ...

@final
class ShapeReport:
    @property
    def path(self) -> str | None: ...
    @property
    def length(self) -> int: ...
    @property
    def group(self) -> str | None: ...
    @property
    def tokens(self) -> int: ...
    @property
    def dominant_period(self) -> int: ...
    @property
    def dominant_strength(self) -> float: ...
    @property
    def regions(self) -> list[ShapeRegion]: ...
    @property
    def change_points(self) -> list[int]: ...
    @property
    def frames(self) -> list[ShapeFrame]: ...
    def to_dict(self) -> dict[str, Any]: ...

def magnitude(
    text: _Text | None = None,
    *,
    path: _Path | None = None,
    lib: _Lib | None = None,
    detail: bool = False,
    jump_threshold: float | None = None,
    outlier_sigma: float | None = None,
) -> MagnitudeReport: ...
def stress(
    text: _Text | None = None,
    *,
    path: _Path | None = None,
    lib: _Lib | None = None,
    detail: bool = False,
    peak_min_depth: int | None = None,
    fracture_min_depth: int | None = None,
) -> StressReport: ...
def flow(
    text: _Text | None = None,
    *,
    path: _Path | None = None,
    lib: _Lib | None = None,
    signal: Literal["magnitude", "stress", "length"] = "magnitude",
    grain: Literal["token", "super"] = "token",
    detail: bool = False,
    analytic: bool = False,
    window: int | None = None,
    steady_band: float | None = None,
) -> FlowReport: ...
def observation(
    text: _Text | None = None,
    *,
    path: _Path | None = None,
    lib: _Lib | None = None,
    grain: _Grain = "byte",
    detail: bool = False,
    contested_threshold: float | None = None,
    contested_min_gap: int | None = None,
) -> ObservationReport: ...
def gravity(
    text: _Text | None = None,
    *,
    path: _Path | None = None,
    lib: _Lib | None = None,
    grain: _Grain = "token",
    top: int = 8,
    detail: bool = False,
) -> GravityReport: ...
def context(
    text: _Text | None = None,
    *,
    path: _Path | None = None,
    lib: _Lib | None = None,
    fold: _Fold = "window",
    token_window: int | None = None,
    unit_window: int | None = None,
    detail: bool = False,
) -> ContextReport: ...
def relation(
    text: _Text | None = None, *, path: _Path | None = None, lib: _Lib | None = None, canonical: bool = False, detail: bool = False
) -> RelationReport: ...
def spectral(
    text: _Text | None = None,
    *,
    path: _Path | None = None,
    classify: bool = False,
    detail: bool = False,
    cp_threshold: float | None = None,
    cp_floor: float | None = None,
    cp_min_gap: int | None = None,
) -> SpectralReport: ...
def seam(
    text: _Text | None = None,
    *,
    path: _Path | None = None,
    order: int | None = None,
    passes: int | None = None,
    english: bool = False,
    detail: bool = False,
    cut_threshold: float | None = None,
) -> SeamReport: ...
def echo(
    text: _Text | None = None,
    *,
    path: _Path | None = None,
    lib: _Lib | None = None,
    group: str = "identity",
    structure: bool = False,
    detail: bool = False,
    max_period_cv: float | None = None,
) -> EchoReport: ...
def orbit(
    text: _Text | None = None,
    *,
    path: _Path | None = None,
    lib: _Lib | None = None,
    group: str = "shape",
    same_as: _Text | None = None,
    detail: bool = False,
) -> OrbitReport: ...
def shape(
    text: _Text | None = None,
    *,
    path: _Path | None = None,
    lib: _Lib | None = None,
    group: str | None = None,
    detail: bool = False,
    template_strength: float | None = None,
) -> ShapeReport: ...
